eureka:
  client:
    # No need to register client with eureka as this is only a client. Not acting as a micro service.
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:123456789@localhost:8761/eureka/}
    enabled: true
  instance:
    hostname: localhost
    preferIpAddress: true

# Sets default logging for logback
logging:
  level:
    root: INFO