eureka:
  client:
    # No need to register client with eureka as this is only a client. Not acting as a micro service.
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:123456789@localhost:8761/eureka/}
    enabled: true
  instance:
    hostname: localhost
    preferIpAddress: true

scenario: 2

# Settings for ribbon - Scenario 1 - Ref Method for pre-requisites and instructions
#ribbon:
#  eureka:
#    enabled: true
#  MaxAutoRetries: 0 # Max number of retries on the same server (excluding the first try)
#  MaxAutoRetriesNextServer: 0 # Max number of next servers to retry (excluding the first server)
#  OkToRetryOnAllOperations: true # Whether all operations can be retried for this client
#  ServerListRefreshInterval: 2000 # Interval to refresh the server list from the source
#  ReadTimeout: 10000 # Connect timeout used by Apache HttpClient
#  ConnectTimeout: 10000 # Read timeout used by Apache HttpClient

# Settings for ribbon - Scenario 2 - Ref Method for pre-requisites and instructions
ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 0 # Max number of retries on the same server (excluding the first try)
  MaxAutoRetriesNextServer: 1 # Max number of next servers to retry (excluding the first server)
  OkToRetryOnAllOperations: true # Whether all operations can be retried for this client
  ServerListRefreshInterval: 2000 # Interval to refresh the server list from the source
  ReadTimeout: 10000 # Connect timeout used by Apache HttpClient
  ConnectTimeout: 10000 # Read timeout used by Apache HttpClient

# Feign is declarative rest client
feign:
  # Hystrix provides circuit breaker capabilities
  hystrix:
    enabled: false

# Sets default logging for logback
logging:
  level:
    root: INFO